"""Runtime contract tests."""
from pathlib import Path
import importlib.util,json,tempfile,unittest
REPO=Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('release_runner',REPO/'run.py')
runner=importlib.util.module_from_spec(spec);spec.loader.exec_module(runner)
class Contracts(unittest.TestCase):
 def setUp(self):
  self.tmp=tempfile.TemporaryDirectory();self.w=Path(self.tmp.name);self.cap=self.w/runner.CAP
  (self.cap/'outputs').mkdir(parents=True)
  self.out=self.cap/'outputs/test.csv.gz';self.out.write_bytes(b'new generated bytes')
  self.static={'file':'inputs/raw.json','sha256':'fixed-input-hash'}
  self.man=self.cap/'HISTORICAL_INPUT_MANIFEST.json'
  self.man.write_text(json.dumps([self.static,{'file':'outputs/test.csv.gz','sha256':'old-serialization-hash'}]))
 def tearDown(self):self.tmp.cleanup()
 def receipt(self):
  (self.w/'COMPLETED_OUTPUT_HASHES.json').write_text(json.dumps({'outputs/test.csv.gz':{'sha256':runner.digest(self.out),'successful_script':'run_raw_stage.py'}}))
 def test_missing_receipt_rejected(self):
  before=self.man.read_bytes()
  with self.assertRaises(RuntimeError):runner.rebind_generated_inputs(self.w,'run_historical_stage.py')
  self.assertEqual(before,self.man.read_bytes())
 def test_rebinding_preserves_static_input_and_old_contract(self):
  self.receipt();old=self.man.read_bytes();runner.rebind_generated_inputs(self.w,'run_historical_stage.py')
  rows=json.loads(self.man.read_text());self.assertEqual(rows[0],self.static)
  self.assertEqual(rows[1]['sha256'],runner.digest(self.out))
  self.assertEqual((self.cap/'original_contracts/HISTORICAL_INPUT_MANIFEST.json').read_bytes(),old)
 def test_tampered_output_rejected(self):
  self.receipt();self.out.write_bytes(b'changed after successful run')
  with self.assertRaises(RuntimeError):runner.rebind_generated_inputs(self.w,'run_historical_stage.py')
if __name__=='__main__':unittest.main()
